const $=s=>document.querySelector(s);
const icon=n=>`<i data-lucide="${n}"></i>`;
const sectionHead=(n,label,title,desc='')=>`<div class="section-heading"><div><div class="section-kicker">${n} / ${label}</div><h2>${title}</h2></div>${desc?`<p>${desc}</p>`:''}</div>`;
const annexData=[
 ['A1','Créer le dossier client','TTN · Onglet Général','Identifier le dossier, le type de transaction import/export, la nature de l’autorisation, l’importateur et le fournisseur. Le dossier est initialisé avant les données complémentaires.'],
 ['A2','Renseigner les données communes','TTN · Données communes','Contrôler les pays de provenance, d’achat et de destination, le déclarant, le mode de livraison, la devise et les montants PFN et FOB avec les pièces commerciales et de transport.'],
 ['A3','Saisir et contrôler les articles','TTN · Article','Vérifier la NDP, la désignation, le pays d’origine, les codes QCS, le prix facturé net en devise et les éléments du PFN. La codification, l’origine et la valeur doivent concorder.'],
 ['A4','L’entête de la déclaration','DDM · Format 01','Contrôler l’identité de l’importateur et du fournisseur, le type de déclaration, le déclarant et les pays de provenance, de vente et de destination.'],
 ['A5','Transport et données financières','DDM · Suite Entête','Rapprocher le transport, l’incoterm, le mode de paiement, la devise, le PFN, les bureaux douaniers et les références du commissionnaire avec les pièces du dossier.'],
 ['A6','Le manifeste et les colis','DDM · Format 05','Renseigner la nature et le nombre des colis, le poids brut, les marques, l’escale, le titre de transport et les références logistiques, en cohérence avec l’Air Waybill.'],
 ['A7','Le détail douanier par article','DDM · Format 07','Contrôler chaque ligne : NDP, désignation du produit, pays d’origine, PFN, poids, régime déclaré, TCE et autres références réglementaires avant validation.'],
 ['B1','La facture fournisseur · 1/2','EDQM · n° 6078CS04','Coordonnées du fournisseur et de MEDIS, informations d’expédition et détail des produits commandés : la première référence commerciale du dossier.'],
 ['B2','La facture fournisseur · 2/2','EDQM · Total et paiement','Suite de la facturation, frais, total net de 370,00 EUR et mention « PAID ». Cette page confirme le montant et le statut de paiement de la facture.'],
 ['B3','La lettre de transport aérien','AWB · n° 020-95331773','Expéditeur, destinataire, itinéraire, poids, numéro AWB et informations d’acheminement : les références logistiques à rapprocher des autres pièces.'],
 ['B4','Facture commerciale & domiciliation','MEDIS · Pièce commerciale','Exportateur, importateur, désignation, montants en devise et en dinars et références de domiciliation utilisés pour les formalités.'],
 ['B5','L’autorisation d’importation','MEDIS · Titre de commerce extérieur','Identités de l’importateur et de l’exportateur, désignation des marchandises, références du dossier et informations liées à l’autorisation.'],
 ['B6','La déclaration en détail','DDM · n° 121024','Synthèse du dédouanement : importateur, fournisseur, transport, désignation, origine, valeurs et régime. La zone du type de déclaration porte la lettre C.']
];
const steps=[
 ['16 JUIL. 2026','Réceptionner & vérifier','La facture EDQM n° 6078CS04 identifie les parties, les produits, les quantités, les prix et les conditions d’expédition. Le montant net du dossier est de 370,00 EUR.','B1','Facture fournisseur'],
 ['20 JUIL. · ARRIVÉE ESTIMÉE','Contrôler le transport','L’Air Waybill n° 020-95331773 permet de comparer l’expéditeur, le destinataire, l’itinéraire, le poids et la nature des marchandises. L’arrivée du 20 juillet est une estimation portée sur l’AWB, pas une arrivée confirmée.','B3','Air Waybill'],
 ['05 AOÛT 2026','Préparer les formalités commerciales','Les données de facture commerciale et les démarches d’autorisation reprennent l’exportateur, l’importateur, la provenance, les montants et la désignation. Vérifier aussi les références de domiciliation.','B4','Facture & domiciliation'],
 ['21 AOÛT 2026','Vérifier l’autorisation','La chronologie du rapport indique une référence d’enregistrement de l’autorisation. Cette pièce complète le dossier et doit être contrôlée avant sa finalisation.','B5','Autorisation d’importation'],
 ['26 AOÛT 2026','Préparer la déclaration sur TTN','La DDM n° 121024 synthétise les parties, les marchandises, les codes tarifaires, les valeurs et les droits ou taxes calculés. Le rapport identifie une déclaration de type C.','B6','Déclaration en détail'],
 ['APRÈS VALIDATION','Suivre le traitement sur SINDA','Suivre l’état du dossier et les contrôles, répondre aux demandes de la douane puis réaliser un contrôle croisé final. La poursuite du dédouanement se fait jusqu’au bon à enlever (BAE).',null,'Comprendre les couloirs']
];
const skills=[['files','Contrôle documentaire','Lire et comparer les documents d’un même dossier.'],['monitor','TTN & SINDA','Préparer les données et suivre le traitement douanier.'],['shield-check','Régimes & privilèges','Vérifier les justificatifs et distinguer C de CF.'],['folders','Organisation','Classer les pièces dans un ordre clair et logique.'],['messages-square','Communication','Demander une vérification et signaler une anomalie.'],['route','Sélectivité douanière','Comprendre les couloirs vert, orange et rouge.']];
const glossary=[['AWB','Air Waybill : lettre de transport aérien.'],['CPT','Carriage Paid To.'],['EDQM','European Directorate for the Quality of Medicines & HealthCare.'],['MEDIS','Les Laboratoires MEDIS.'],['NDP','Nomenclature douanière des produits.'],['SINDA','Système informatique utilisé pour le traitement et le suivi douanier.'],['TTN','Tunisie TradeNet.'],['BAE','Bon à enlever.'],['C','Mise à la consommation avec paiement des droits et taxes selon le régime de droit commun.'],['CF','Mise à la consommation avec bénéfice d’un régime fiscal privilégié.'],['DDM','Déclaration en détail des marchandises.']];
$('#content').innerHTML=`
<section class="section" id="cadre">${sectionHead('01','LE CADRE DU STAGE','Le terrain, au-delà de la théorie.','Comprendre le métier de formaliste douanier, de la réception des pièces au suivi du dédouanement.')}<div class="company-grid"><div class="company-story"><span class="tag">L’ORGANISME D’ACCUEIL</span><h3>KS TRANSIT<span>Le lien entre tous les acteurs.</span></h3><p>STE Khaled Sahli Transit est une société tunisienne spécialisée dans le transit, la logistique et les formalités douanières. Commissionnaire en douane agréé, elle coordonne importateurs, transporteurs, services portuaires et administrations douanières.</p><div class="company-meta"><span><strong>2011</strong>Création · SARL</span><span><strong>Tunis</strong>33, rue Lénine, 1001</span><span><strong>Khaled Sahli</strong>Direction</span></div><details><summary>Voir l’organigramme original ${icon('plus')}</summary><img class="org-image" src="assets/organigramme.png" alt="Organigramme de KS TRANSIT reproduit du rapport, figure 1" loading="lazy"><a class="source-link" href="assets/rapport-stage.pdf#page=11" target="_blank" rel="noopener">Figure 1 · rapport, p. 3 ↗</a></details></div><div class="mission-card"><div class="section-kicker">LA MISSION DU TRANSITAIRE</div><h3>Une chaîne de confiance.</h3>${[['01','Recevoir & contrôler','Pièces commerciales, transport, références, quantités et valeurs.'],['02','Préparer & communiquer','Données de déclaration, pièces manquantes et corrections avec le client.'],['03','Suivre & archiver','État du dossier, autorisations, régimes particuliers et trace des opérations.']].map(x=>`<div class="mission-row"><span>${x[0]}</span><div><strong>${x[1]}</strong><p>${x[2]}</p></div></div>`).join('')}</div></div><div class="objective"><span>${icon('target')} OBJECTIF DU STAGE</span><p>Comprendre le circuit d’importation, lire les pièces, pratiquer TTN et SINDA, vérifier les privilèges et comprendre les déclarations C/CF ainsi que la sélectivité douanière.</p></div><p class="source-note">Source : chapitre I, p. 2–4 du rapport. Les informations sur l’entreprise sont celles présentées dans le rapport.</p></section>
<section class="section pale" id="parcours">${sectionHead('02','LE DOSSIER MEDIS','Un dossier. Six étapes clés.','Des réactifs et des standards de laboratoire, du Conseil de l’Europe – EDQM à Strasbourg aux Laboratoires MEDIS à Nabeul.')}<div class="journey-grid"><aside class="case-summary"><span class="tag">LE CAS ÉTUDIÉ</span><h3>MEDIS <span>× EDQM</span></h3><dl><div><dt>Marchandises</dt><dd>Réactifs & standards de laboratoire</dd></div><div><dt>Facture</dt><dd>6078CS04 · 16/07/2026</dd></div><div><dt>Montant net</dt><dd class="case-amount">370,00 EUR</dd></div><div><dt>Transport</dt><dd>Aérien · 020-95331773</dd></div><div><dt>Déclaration</dt><dd>121024 · 26/08/2026 · C</dd></div></dl><span class="source-note">Chapitre III · p. 8–11</span></aside><div class="timeline">${steps.map((s,i)=>`<article class="timeline-item"><span class="step-number">0${i+1}</span><div><small>${s[0]}</small><h3>${s[1]}</h3><p>${s[2]}</p>${s[3]?`<button class="inline-link" data-doc="${s[3]}">${icon('file-text')} ${s[4]} <span>${s[3]} ↗</span></button>`:`<a class="inline-link" href="#douane">${s[4]} ${icon('arrow-right')}</a>`}</div></article>`).join('')}</div></div></section>
<section class="section" id="outils">${sectionHead('03','LE TRAVAIL AU QUOTIDIEN','Deux outils. Deux rôles complémentaires.','Préparer correctement le dossier et comprendre son avancement auprès de la douane.')}<div class="tools-grid"><article class="tool-card"><div class="tool-heading"><span class="tool-logo">TTN</span><span class="tag">PRÉPARER</span></div><h3>Tunisie TradeNet</h3><p>Ouvrir et organiser le dossier, identifier l’importateur et le fournisseur, renseigner les données communes et préparer la déclaration.</p><ul><li>Transaction, client, fournisseur et pays.</li><li>Devise, montants, articles et déclaration en détail.</li><li>Comparer chaque saisie aux documents avant validation.</li></ul><button data-doc="A1" class="inline-link">Découvrir l’interface ${icon('arrow-up-right')}</button></article><article class="tool-card dark-tool"><div class="tool-heading"><span class="tool-logo">SINDA</span><span class="tag">SUIVRE</span></div><h3>Le suivi douanier</h3><p>Consulter l’état d’avancement, les opérations et les contrôles déjà effectués ; repérer une attente ou une action supplémentaire.</p><ul><li>Suivre le traitement auprès de la douane.</li><li>Consulter un privilège ou régime particulier s’il existe.</li><li>Signaler les incohérences au responsable habilité.</li></ul><p class="tool-note">La validation finale reste sous la responsabilité des personnes habilitées.</p></article></div><div class="practice-grid"><div><h3>D’abord observer.</h3><p>Réception des pièces → contrôle des noms, références, quantités, valeurs et dates → préparation des données → suivi informatique → contrôle final.</p></div><div><h3>Puis participer, sous supervision.</h3><p>Classer le dossier MEDIS, vérifier la facture EDQM et les commandes, contrôler l’AWB, participer à la facture commerciale, préparer la DDM, utiliser TTN et SINDA, consulter les privilèges et archiver après contrôle croisé.</p></div></div><div class="section-kicker gallery-kicker">LES ÉCRANS DU STAGE · A1 À A7</div><div class="swiper ttn-slider"><div class="swiper-wrapper">${annexData.slice(0,7).map(a=>`<article class="swiper-slide screen-card"><button class="screen-image" data-doc="${a[0]}" aria-label="Agrandir ${a[0]} : ${a[1]}"><img src="assets/${a[0]}.png" alt="Capture ${a[0]} : ${a[2]}" loading="lazy"><span>${icon('expand')}</span></button><div class="screen-body"><small>${a[0]} · ${a[2]}</small><h3>${a[1]}</h3><p>${a[3]}</p>${['A4','A5','A6','A7'].includes(a[0])?'<span class="illustration-label">Dossier d’illustration distinct de MEDIS</span>':''}</div></article>`).join('')}</div><div class="slider-footer"><span>7 interfaces originales, étape par étape</span><div><button class="small-button slider-prev" aria-label="Capture précédente">←</button><button class="small-button slider-next" aria-label="Capture suivante">→</button></div></div></div></section>
<section class="section navy-section" id="douane">${sectionHead('04','COMPRENDRE LA DOUANE','Une déclaration, puis un circuit de contrôle.','Les notions étudiées pendant le stage, telles qu’elles sont expliquées dans le rapport.')}<div class="regime-grid"><article><span class="regime-letter">C</span><div><span class="tag">LE CAS MEDIS</span><h3>Le régime de droit commun</h3><p>Mise à la consommation de marchandises étrangères avec paiement des droits et taxes selon le régime de droit commun. L’annexe B6 porte la lettre C.</p></div></article><article><span class="regime-letter">CF</span><div><span class="tag">AVEC PRIVILÈGE FISCAL</span><h3>Un régime fiscal privilégié</h3><p>Franchise totale ou partielle lorsque les conditions et justificatifs requis sont remplis. Vérifier le régime et les pièces avant validation.</p></div></article></div><div class="customs-intro"><h3>Après validation de la DDM</h3><p>La sélectivité affecte automatiquement un couloir à la déclaration. Un contrôle ne signifie pas nécessairement qu’une erreur a été commise.</p></div><div class="lanes"><article class="lane green"><span>01 / COULOIR VERT</span>${icon('circle-check')}<h3>Bon à enlever</h3><p>Émission du BAE sous réserve de l’accomplissement des formalités et du paiement des droits et taxes exigibles.</p></article><article class="lane orange"><span>02 / COULOIR ORANGE</span>${icon('file-search')}<h3>Contrôle documentaire</h3><p>La douane contrôle la déclaration et les pièces justificatives. Le transitaire répond aux demandes et fournit les compléments.</p></article><article class="lane red"><span>03 / COULOIR ROUGE</span>${icon('package-search')}<h3>Contrôle physique</h3><p>Visite de la marchandise en plus des vérifications nécessaires. La suite du dédouanement dépend de la décision douanière.</p></article></div><p class="notice">${icon('info')} Le couloir effectivement attribué au dossier MEDIS n’est pas établi par les pièces du rapport. Ces trois circuits présentent le fonctionnement général observé.</p><p class="source-note">Source : chapitre III, p. 9–10. Présentation pédagogique du rapport, sans actualisation réglementaire.</p></section>
<section class="section" id="acquis">${sectionHead('05','LES ACQUIS DU STAGE','Vérifier avant de valider.','Rigueur, organisation et communication : les compétences développées au fil des dossiers.')}<div class="skills-grid">${skills.map(s=>`<article>${icon(s[0])}<h3>${s[1]}</h3><p>${s[2]}</p></article>`).join('')}</div><div class="best-practices"><div><span class="section-kicker">LES BONNES PRATIQUES</span><h3>Anticiper les erreurs.<br>Éviter les retards.</h3><p>Le contrôle final rapproche importateur, fournisseur, références, désignation, quantités, valeurs, transport, autorisation et déclaration.</p></div><div class="risk-list">${[['Document manquant','Utiliser une checklist avant la saisie.'],['Informations différentes entre deux pièces','Faire un contrôle croisé.'],['Autorisation non prête','Anticiper les démarches.'],['Erreur de saisie TTN','Vérifier avant validation.'],['Dossier bloqué ou en attente','Consulter régulièrement SINDA.'],['Privilège non visible ou incohérent','Vérifier l’information et informer le responsable.']].map(a=>`<div><span>${a[0]}</span><strong>${icon('check')} ${a[1]}</strong></div>`).join('')}</div></div><blockquote>« Ce travail demande surtout de la rigueur, de l’organisation et une bonne comparaison des informations entre les différents documents. »<cite>Conclusion générale · rapport, p. 12</cite></blockquote><p>Le stage a permis de mettre en pratique la formation, de développer le sens des responsabilités et le travail en équipe, et de comprendre le métier de formaliste douanier. Les recommandations finales : une checklist simple, un classement clair et un suivi régulier jusqu’à la clôture.</p></section>
<section class="section pale" id="annexes">${sectionHead('06','LES DOCUMENTS ORIGINAUX','Le dossier, pièces à l’appui.','Les 13 annexes du rapport, avec leur rôle pédagogique et leur page d’origine. Cliquez sur une pièce pour l’agrandir.')}<div class="annex-tabs" role="group" aria-label="Catégorie d’annexes"><button class="active" data-filter="all" aria-pressed="true">Toutes les pièces <span>13</span></button><button data-filter="A" aria-pressed="false">Interfaces TTN <span>7</span></button><button data-filter="B" aria-pressed="false">Dossier MEDIS <span>6</span></button></div><p class="source-note">A4 à A7 : dossier d’illustration distinct du dossier MEDIS, conservé pour montrer les rubriques de la DDM.</p><div class="annex-grid">${annexData.map((a,i)=>`<button class="annex-card" data-doc="${a[0]}" data-category="${a[0][0]}"><div class="annex-image"><img src="assets/${a[0]}.png" alt="${a[2]}" loading="lazy"><span class="annex-ref">${a[0]}</span><span class="expand-icon">${icon('expand')}</span></div><div class="annex-body"><small>${a[0][0]==='A'?'INTERFACE TTN':'PIÈCE JUSTIFICATIVE'} · PDF P. ${i+23}</small><h3>${a[1]}</h3><span>Consulter le document ${icon('arrow-up-right')}</span></div></button>`).join('')}</div><div class="full-report"><div>${icon('book-open')}<div><h3>Le rapport dans son intégralité</h3><p>36 pages · textes, organigramme, remerciements, dédicaces, références et annexes.</p></div></div><a class="button" href="assets/rapport-stage.pdf" target="_blank" rel="noopener">Ouvrir le PDF ${icon('arrow-up-right')}</a></div><details class="full-text"><summary>Consulter le texte intégral du rapport ${icon('plus')}</summary><div id="report-text"><p>Chargement du texte…</p></div></details></section>
<section class="section compact-section" id="lexique">${sectionHead('07','LES REPÈRES','Le vocabulaire du dossier.')}<div class="glossary">${glossary.map(g=>`<details><summary>${g[0]} ${icon('plus')}</summary><p>${g[1]}</p></details>`).join('')}</div><details class="references"><summary>Références utilisées dans le rapport ${icon('plus')}</summary><ol><li>DIWANI Ichraf, Guide de rédaction d’un rapport de stage en Formalités douanières, IPSET, 2025–2026.</li><li>EDQM – Conseil de l’Europe, facture n° 6078CS04 du 16/07/2026.</li><li>Air Waybill n° 020-95331773.</li><li>Facture commerciale et document de domiciliation du dossier MEDIS.</li><li>Autorisation d’importation et titre de commerce extérieur du dossier MEDIS.</li><li>Tunisie TradeNet, DDM n° 121024 du 26/08/2026.</li><li>Captures TTN et notes de stage chez KS TRANSIT.</li><li>Direction Générale des Douanes Tunisiennes, Manuel des procédures à l’importation : sélectivité automatique et couloirs.</li><li>Direction Générale des Douanes Tunisiennes, Procédures de dédouanement et Guide de l’utilisateur DPF : déclarations CF et privilèges fiscaux.</li></ol><p class="source-note">Références reproduites de la p. 13 du rapport ; ce site s’appuie sur le document fourni.</p></details></section>
<section class="section quiz-section" id="qcm"><div class="quiz-intro"><div class="section-kicker">08 / À VOUS DE JOUER</div><h2>Du dossier<br>aux bons réflexes.</h2><p>Vous avez suivi le parcours.<br>Testez maintenant vos connaissances.</p><div class="quiz-spec"><span>${icon('list-checks')} 15 questions</span><span>${icon('message-circle')} Corrections expliquées</span><span>${icon('clock-3')} À votre rythme</span></div><p class="quiz-help">Une seule bonne réponse par question.<br>Le score porte sur votre premier choix validé.</p></div><div class="quiz-card" id="quiz-card" aria-live="polite"></div></section>`;

const questions=[
 ['Quel est le rôle principal du transitaire ?',['Fabriquer les produits chimiques','Préparer et suivre les formalités entre les acteurs','Fixer les règles douanières'],1,'Le transitaire contrôle les pièces, prépare les données et suit le dossier en relation avec les différents acteurs.','I.3 · p. 3'],
 ['Qui est le fournisseur du dossier MEDIS ?',['KS TRANSIT à Tunis','IPSET','Conseil de l’Europe – EDQM à Strasbourg'],2,'Le fournisseur est le Conseil de l’Europe – EDQM à Strasbourg ; MEDIS est l’importateur à Nabeul.','III.1 · p. 8'],
 ['Quel est le montant net de la facture EDQM ?',['370,00 EUR','370,00 TND','3 700,00 EUR'],0,'La facture n° 6078CS04 du 16/07/2026 indique un montant net de 370,00 EUR.','III.2.A · p. 8 / B2'],
 ['Quel document décrit le transport aérien ?',['La DDM','L’Air Waybill','La domiciliation'],1,'L’AWB porte les informations d’expéditeur, destinataire, itinéraire, poids et acheminement.','III.2.B · p. 8 / B3'],
 ['À quoi sert principalement TTN pendant ce stage ?',['Organiser et préparer les données du dossier','Effectuer la visite physique des marchandises','Fabriquer les standards de laboratoire'],0,'TTN sert à créer et organiser le dossier et à préparer les données des formalités et de la déclaration.','II.3 · p. 5–6'],
 ['Quel est le rôle de SINDA dans le rapport ?',['Émettre la facture fournisseur','Choisir le fournisseur','Suivre l’état du dossier auprès de la douane'],2,'SINDA permet de consulter l’avancement, les opérations et les contrôles effectués.','II.4 · p. 6'],
 ['Que faut-il faire avant de valider une saisie dans TTN ?',['Contrôler uniquement le nom du client','Comparer les données aux pièces du dossier','Se fier au montant sans regarder les autres rubriques'],1,'Il faut contrôler transaction, parties, pays, devise, montants et articles avec les documents.','II.3 · p. 6'],
 ['Quel type de déclaration est identifié pour MEDIS ?',['C','CF','Le rapport ne le précise pas'],0,'L’annexe B6 porte la lettre C ; le rapport présente la DDM n° 121024 comme une déclaration C.','III.2.F · p. 9 / B6'],
 ['Que distingue une déclaration CF ?',['Elle concerne toujours un transport aérien','Elle ne nécessite aucun justificatif','Elle bénéficie d’un régime fiscal privilégié sous conditions'],2,'Le régime CF peut prévoir une franchise totale ou partielle, sous réserve des conditions et justificatifs requis.','III.2.F · p. 9'],
 ['Que prévoit le couloir orange ?',['Une livraison immédiate sans formalités','Un contrôle documentaire','Uniquement une visite physique'],1,'Le couloir orange correspond au contrôle de la déclaration et des pièces justificatives.','III.3 · p. 10'],
 ['Que prévoit le couloir rouge ?',['Un contrôle physique de la marchandise','L’annulation automatique de la déclaration','L’absence de vérifications'],0,'Le couloir rouge prévoit la visite de la marchandise, en plus des vérifications nécessaires. Il ne prouve pas à lui seul une erreur.','III.3 · p. 10'],
 ['Le couloir vert dispense-t-il du paiement des droits exigibles ?',['Oui, dans tous les cas','Oui, si le dossier vient de TTN','Non, le BAE reste soumis aux formalités et paiements exigibles'],2,'Le rapport précise que le BAE est émis sous réserve de l’accomplissement des formalités et du paiement des droits et taxes exigibles.','III.3 · p. 10'],
 ['Quel couloir a réellement été attribué au dossier MEDIS ?',['Vert','Impossible à établir avec certitude à partir du rapport','Rouge'],1,'Les pièces reproduites ne permettent pas d’identifier avec certitude le couloir effectivement attribué à MEDIS.','III.3 · p. 10'],
 ['Les captures A4 à A7 représentent-elles nécessairement le dossier MEDIS ?',['Non, elles présentent un dossier d’illustration distinct','Oui, toutes les captures concernent MEDIS','Elles sont des factures EDQM'],0,'Le rapport précise que A4 à A7 illustrent les rubriques de la DDM à partir d’un dossier distinct.','Annexes · p. 14'],
 ['Un privilège est incohérent ou absent. Quel est le bon réflexe ?',['Valider sans vérification','Modifier seul le régime applicable','Vérifier et informer le responsable'],2,'Les stagiaires consultent les informations et signalent les anomalies ; la validation finale appartient aux personnes habilitées.','II.4 · p. 6 / III.5 · p. 11']
];
let quizIndex=0, selected=null, answers=[], validated=false, quizStarted=false;
function renderQuiz(){
 const box=$('#quiz-card');
 if(!quizStarted){box.innerHTML=`<div class="quiz-start"><span class="quiz-start-icon">${icon('graduation-cap')}</span><span class="tag">LE DÉFI DU FORMALISTE</span><h3>Prêt à faire le point ?</h3><p>Documents, outils, régimes et couloirs douaniers : retrouvez les notions essentielles du stage.</p><button class="button mint" id="start-quiz">Commencer le QCM ${icon('arrow-right')}</button><small>Sans inscription · Pas de chronomètre</small></div>`;}
 else if(quizIndex>=questions.length){const score=answers.filter((a,i)=>a===questions[i][2]).length;box.innerHTML=`<div class="quiz-result"><span class="tag">PARCOURS TERMINÉ</span><div class="score">${score}<span>/ ${questions.length}</span></div><h3>${score>=12?'De solides réflexes !':score>=8?'Les bases sont là.':'Une nouvelle lecture pour progresser.'}</h3><p>${score>=12?'Vous maîtrisez les points essentiels de ce dossier.':'Relisez les explications ci-dessous, puis retentez le QCM.'}</p><button class="button" id="restart-quiz">Recommencer ${icon('rotate-ccw')}</button></div><details class="quiz-review" open><summary>Revoir mes 15 réponses</summary>${questions.map((q,i)=>`<article class="review-item ${answers[i]===q[2]?'correct':'incorrect'}"><strong>${i+1}. ${q[0]}</strong><p>Votre réponse : ${q[1][answers[i]]}</p><p><b>Bonne réponse : ${q[1][q[2]]}</b><br>${q[3]}</p><small>Source : ${q[4]}</small></article>`).join('')}</details>`;if(score>=12&&window.confetti&&!matchMedia('(prefers-reduced-motion: reduce)').matches)confetti({particleCount:80,spread:65,colors:['#68e4c1','#0c2635','#f4b65c'],origin:{y:.7}});}
 else {const q=questions[quizIndex];box.innerHTML=`<div class="quiz-top"><span>QUESTION ${String(quizIndex+1).padStart(2,'0')} / ${questions.length}</span><span>${Math.round(quizIndex/questions.length*100)} %</span></div><div class="quiz-progress" role="progressbar" aria-label="Progression du QCM" aria-valuenow="${quizIndex}" aria-valuemin="0" aria-valuemax="15"><span style="width:${quizIndex/questions.length*100}%"></span></div><h3 tabindex="-1" id="quiz-question">${q[0]}</h3><div class="quiz-options" role="group" aria-labelledby="quiz-question">${q[1].map((o,i)=>`<button data-answer="${i}" aria-pressed="${selected===i}" ${validated?'disabled':''} class="quiz-option ${selected===i?'selected':''} ${validated&&i===q[2]?'is-correct':''} ${validated&&selected===i&&i!==q[2]?'is-wrong':''}"><span>${String.fromCharCode(65+i)}</span>${o}${validated&&i===q[2]?icon('check'):''}</button>`).join('')}</div>${validated?`<div class="quiz-feedback ${selected===q[2]?'correct':'incorrect'}"><strong>${selected===q[2]?'Bonne réponse.':'À retenir.'}</strong><p>${q[3]}</p><small>Source : ${q[4]}</small></div><button class="button" id="next-question">${quizIndex===14?'Voir mon résultat':'Question suivante'} ${icon('arrow-right')}</button>`:`<div class="quiz-bottom"><span>Une seule réponse possible</span><button class="button" id="validate-answer" ${selected===null?'disabled':''}>Valider ${icon('check')}</button></div>`}`;}
 refreshIcons();
}
function startQuiz(){quizStarted=true;quizIndex=0;answers=[];selected=null;validated=false;renderQuiz();$('#quiz-question')?.focus({preventScroll:true});}
function refreshIcons(){window.lucide?.createIcons();}
let documentIndex=0;
function showDocument(id){const i=annexData.findIndex(a=>a[0]===id);if(i<0)throw new Error('Annexe inconnue');documentIndex=i;const a=annexData[i];$('#document-ref').textContent=`ANNEXE ${a[0]} · PDF PAGE ${i+23}`;$('#document-title').textContent=a[1];$('#document-img').src=`assets/${a[0]}.png`;$('#document-img').alt=`Annexe ${a[0]} — ${a[2]}`;$('#document-caption').textContent=a[3]+(i>=3&&i<=6?' Dossier d’illustration distinct du dossier MEDIS.':'');$('#document-original').href=`assets/rapport-stage.pdf#page=${i+23}`;$('#prev-document').disabled=i===0;$('#next-document').disabled=i===12;if(!$('#document-dialog').open)$('#document-dialog').showModal();}
document.addEventListener('click',e=>{const doc=e.target.closest('[data-doc]');if(doc)showDocument(doc.dataset.doc);const opt=e.target.closest('[data-answer]');if(opt&&!validated){selected=Number(opt.dataset.answer);renderQuiz();$(`[data-answer="${selected}"]`).focus({preventScroll:true});}if(e.target.closest('#start-quiz,#restart-quiz'))startQuiz();if(e.target.closest('#validate-answer')&&selected!==null&&!validated){validated=true;answers[quizIndex]=selected;renderQuiz();$('#next-question').focus({preventScroll:true});}if(e.target.closest('#next-question')){quizIndex++;selected=null;validated=false;renderQuiz();$('#quiz-question')?.focus({preventScroll:true});}const filter=e.target.closest('[data-filter]');if(filter){document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b===filter);b.setAttribute('aria-pressed',String(b===filter));});document.querySelectorAll('[data-category]').forEach(c=>c.hidden=filter.dataset.filter!=='all'&&c.dataset.category!==filter.dataset.filter);}});
$('.close-dialog').onclick=()=>$('#document-dialog').close();$('#prev-document').onclick=()=>showDocument(annexData[documentIndex-1][0]);$('#next-document').onclick=()=>showDocument(annexData[documentIndex+1][0]);$('#document-dialog').addEventListener('click',e=>{if(e.target===$('#document-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
$('.menu-toggle').onclick=()=>{const open=$('nav').classList.toggle('open');$('.menu-toggle').setAttribute('aria-expanded',String(open));};document.querySelectorAll('nav a').forEach(a=>a.onclick=()=>{$('nav').classList.remove('open');$('.menu-toggle').setAttribute('aria-expanded','false');});
renderQuiz();
if(window.Swiper)new Swiper('.ttn-slider',{slidesPerView:1,spaceBetween:20,keyboard:{enabled:true,onlyInViewport:true},navigation:{nextEl:'.slider-next',prevEl:'.slider-prev'},breakpoints:{650:{slidesPerView:2},1100:{slidesPerView:3}},a11y:{prevSlideMessage:'Capture précédente',nextSlideMessage:'Capture suivante'}});
if(window.gsap&&!matchMedia('(prefers-reduced-motion: reduce)').matches){gsap.from('.hero-content>*',{y:20,opacity:0,duration:.75,stagger:.09,ease:'power2.out'});gsap.from('.hero-visual',{y:25,opacity:0,duration:1,delay:.2});}
function updateProgress(){const max=document.documentElement.scrollHeight-innerHeight;$('.reading-progress').style.width=`${max>0?scrollY/max*100:0}%`;}
addEventListener('scroll',updateProgress,{passive:true});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+e.target.id));}),{rootMargin:'-20% 0px -65% 0px'});document.querySelectorAll('section[id]').forEach(s=>observer.observe(s));
fetch('assets/report.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then(pages=>{const frag=document.createDocumentFragment();pages.forEach(p=>{const d=document.createElement('details');const summary=document.createElement('summary');summary.textContent=`Page PDF ${p.page}`;const text=document.createElement('div');text.className='original-text';text.textContent=p.text;d.append(summary,text);frag.append(d);});$('#report-text').replaceChildren(frag);}).catch(()=>{$('#report-text').innerHTML='<p>Le texte ne peut pas être chargé. <a href="assets/rapport-stage.pdf" target="_blank" rel="noopener">Consulter le rapport PDF complet.</a></p>';});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'open_report_annex',title:'Ouvrir une annexe du rapport',description:'Ouvre la pièce originale choisie dans la visionneuse.',inputSchema:{type:'object',properties:{annex:{type:'string',enum:annexData.map(a=>a[0])}},required:['annex'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||typeof input.annex!=='string'||Object.keys(input).some(k=>k!=='annex'))throw Error('Indiquer une référence A1 à A7 ou B1 à B6.');showDocument(input.annex);return{opened:input.annex};}})).catch(()=>{});}catch{}}
